import React from 'react';

function ScoreCard() {

  function handleClick(e) {
    e.preventDefault();
    alert(`Clicked ${e.target.value}`)
  }

  return (
    <div>
      <div>
        <h4>Score:</h4>
      </div>
      <div>
        <div>
          Frame1
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame2
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame3
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame4
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame5
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame6
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame7
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame8
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame9
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
        *******
        <div>
          Frame10
          <div>
            Roll1
          </div>
          <div>
            Roll2
          </div>
        </div>
      </div>
    </div>
  )
}

export default ScoreCard;